### ISSUE TITLE
Implement python project structure 

### ISSUE THREAD

**Issue by FilipAndreiMarius** [AlexThePav/python-test#1]
1.Project requirements:Python 3.7 and pip3

Structure example 
foo -project name
├── foo modul de baza
│   ├── main.py
│   ├── __init__.py
│  
├── README
└── setup.py
2.Define a console script entry point in setup.py to run it from console
Example 
https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html

3.In main.py define a print to know that the project runs

**Comment by AlexThePav** [comment]
Done
