### ISSUE TITLE
Define Pytest pluggin 

### ISSUE THREAD

**Issue by FilipAndreiMarius** [AlexThePav/python-test#2]
1.add pytest as project dependency
2.Create a python class in the scripts module and define the main pytest hooks and add a print on each state

Example:

 def pytest_sessionstart(self, session):
        """Called after the 'Session' object has been created and before performing test collection.
        :param _pytest.main.Session session: the pytest session object.
        """

    def pytest_sessionfinish(self, session):
        """ called after whole test run finished, right before returning the exit status to the system.
        :param _pytest.main.Session session: the pytest session object.
        :param int exitstatus: the status which pytest will return to the system.
        """
    def pytest_runtest_setup(self, item):
        pass

3.Create a test module on the same line with the script module and add a pytest test file format with an empty method
Ex
def test_something():
     print("Test is runninng!!!)
     pass

4.Add an entry point for pytest in main.py to load the pluggin

Example
def main():
    my_plugin = BaseTarget()

    pytest.main(get_pytest_args(), plugins=[my_plugin]);

def get_pytest_args():
    pytest_args = []
    pytest_args.append('-vs')
    pytest_args.append('./tests')

    return pytest_args

5.Run the test created on line 3

**Comment by AlexThePav** [comment]
Done
